config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "articles#index"
  resources :articles do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update] 
end

app/models/article.rb
class Article < ApplicationRecord
  validates :sentence, presence: true

  belongs_to       :user
  has_many         :comments, dependent: :destroy
  has_one_attached :image

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, only: [:edit]

  def index
    @articles = Article.includes(:user).order("created_at DESC")
  end
  
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.includes(:user).order("created_at DESC")
  end

  def search
    @articles = SearchArticlesService.search(params[:keyword])
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if user_signed_in? && current_user.id == @article.user_id
      @article.destroy
      redirect_to root_path
    else
      render :show
    end
  end


  private
  def article_params
    params.require(:article).permit(:image,:sentence).merge(user_id:current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def move_to_index
    unless user_signed_in? && current_user.id == @article.user_id
      redirect_to root_path
    end
  end
end

app/views/articles/_form.html.erb
<div class="post-form">
  <%= form_with model: @article, local: true do |f| %>
    <div id="image-list"></div>
    <%= f.file_field :image, placeholder: "Image Url", id: "image-form" , class:"image_form"%>
    <%= f.text_area :sentence, placeholder: "text", rows: "10", class: "text-form" %>
    <%= f.submit "SEND", class: "send-form" %>
  <% end %>
</div> 

app/views/articles/_head-name.html.erb
<div class="title-name">
  <h1><%=link_to("Hi-there", root_path, class: "top_skip")%></h1>
</div>

app/views/articles/_send-form.html.erb
<div class="chat-form"> 
  <div class="send-info">
    <div class="send-lists">
      <li class="name">
        <%= image_tag article.user.image, class:"icon" %>
        <%= link_to article.user.nickname ,user_path(article.user_id),class: "nick-name" %>
      </li>
      <div class="image">
        <%= link_to image_tag(article.image, class: "item-img"),article_path(article.id) if article.image.attached?%>
      </div>
    </div>
    <div class = contents>
      <p class="break-all">
        <%= link_to article.sentence,article_path(article.id),class:"sentence-all"%>
      </p>
    </div>
  </div>
</div>

app/views/articles/_side-bar.html.erb
<div class="side-bar-header">
  <div class="header-name-icon">
    <%= image_tag current_user.image, class:"icon" %>
  </div>
  <div class="header-name">
    <%= link_to current_user.nickname, class:"nickname"%>
  </div>

</div>

app/views/articles/edit.html.erb
<div class="title-name">
  <h1>Hi-there</h1>
</div>
<div class="second-title">
  <h5>~edit page~</h5>
</div>
<div class="container">
  <div>
    <%= render partial:"form",locals: {article: @article}%>
  </div>
</div>

app/views/articles/index.html.erb
<div class="main-page">  
  <div class="title-name">
    <h1>Hi-there<h1>

  </div>
  <div class="wrapper">
    <div class="side-bar">
      <%= render partial: "side-bar"%>
    
      <div class="options">
        <ul class="lists">
          <li class="list"><%= link_to "My account",user_path(current_user.id),class: "option" %></li>
          <li class="list"><%= link_to "post", new_article_path, class: "option"%></li>
        </ul>
      </div>
    </div>
    <div class="chat">
      <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
        <%= f.text_field :keyword, class: "search-input" %>
        <%= f.submit "search", class: "search-btn" %>
      <% end %>

      <div class="contents-row">
        <% @articles.each do |article| %>
          <%= render partial: "send-form", locals: { article: article } %>
        <% end %>
      </div>
    </div>
  </div>
</div>
  

app/views/articles/new.html.erb
<div class="new-post"> 
  <%= render "head-name"%>

  <div class="contents">  
    <div class="contents row">
      <h4 class="post-page">post page</h4>
      <%= render "shared/error_messages",model: @article %>
      <div class="container">
        <%= render partial: "form",locals: {article: @article},class: "form"%>
      </div>
    </div>
  </div>
</div>

app/views/articles/search.html.erb
<%= render partial: "top-page"%>

app/views/articles/show.html.erb
<%= render "head-name"%>
<div class="base-row">
  <div class="base">
    <div class="contents row">
      <%if user_signed_in? && current_user.id == @article.user.id %> 
        <div class="more">
          <div class="more_lists">
            <div class="edit-page">
              <%= link_to 'edit', edit_article_path(@article.id), class: "edit" %>
            </div>
            <div class="destroy-page">
              <%= link_to 'delete', article_path(@article.id), class: "destroy", method: :delete %>
            </div>
          </div>
        </div>
      <%end%>
    </div> 
    <div class="image">
      <%= image_tag @article.image.variant(resize: '380x380'), class: "item-img" if @article.image.attached? %>
    </div>
    <div class=contents>
      <p class="break-all">
        <%= @article.sentence %>
      </p>
    </div>
    <div class = "comments">
      <% if user_signed_in? %>
        <%= form_with(model: [@article,@comment],local: true) do |f|%>
          <div class="comment-form">
            <div class="field">
              <%= f.text_field :comment %>
            </div>
            <div class="actions">
              <%= f.submit "comment", src:"airport.png", class: :form_btn %>
            </div>
          </div>
        <% end %> 
      <%end%>
    </div>
    <div class="total-the-number">
      <div class="total-length">
        <%= "View all #{@comments.length} comments" %>
      </div>
    </div>
    <div class= "comments-all-lists">
      <div class="comments-all">
        <div class="comments_lists">
          <% @comments.each do |comment| %>
            <div class="comments_list">
              <%= link_to comment.user.nickname, user_path(comment.user.id), class:"comment_user" %>
              <%= comment.comment %>
            </div>
          <%end%>
       </div>
      </div>
    </div>
  </div>
</div>