config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "articles#index"
  resources :articles do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update] 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  extend ActiveHash::Associations::ActiveRecordExtensions
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX#, message: 'には英字と数字の両方を含めて,設定してください' 

  with_options presence: true do
    validates :nickname
    validates :country_id
  end
  belongs_to_active_hash :country
  belongs_to_active_hash :gender
  has_many :room_users
  has_many :room, through: :room_users
  has_many :articles
  has_many :comments
  has_many :messages
  has_one_attached :image
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only: [:show, :edit, :update]

  def show
    @articles = @user.articles
    
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:image, :nickname, :self_introduction, :country_id, :gender_id, :age, :email, :password)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_show-form.html.erb
<div class="chat-from"> 
  <div class="send-info">
    <div class="send-lists">
      <div class="">
        <%= link_to image_tag(article.image, class: "item-img"),article_path(article.id) if article.image.attached?%>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class="account-form">
    <div class='account-page__inner clearfix'>
      <div class='account-page__inner--left account-page__header'>
        <h2>Edit My Account</h2>
      </div>
    </div>

    <div class='account-page__inner--right user-form'>
      <%= form_with(model: @user, url: user_path, class: 'registration-main', local: true) do |f|%>
      <%= render 'shared/error_messages', model: @user %>
        <div class="post-image">
          <div id="image-list"></div>
          <%= f.file_field :image, placeholder: "Image Url", id: "image-form" %>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :self_introduction%>
          </div>
          <div class='field-input'>
            <%= f.text_area :self_introduction, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :country_id%>
          </div>
          <%= f.collection_select(:country_id, Country.all, :id, :name, {}, {class:'field-input'}) %>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :gender_id%>
          </div>
          <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:'field-input'}) %>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :age%>
          </div>
          <div class='field-input'>
            <%= f.text_field :age, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :password%>
            <i>/Password must contain alpha-numeral(6 or more characters)/</i>
          </div>
          <div class='field-input'>
            <%= f.password_field :password, autocomplete: "off"%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :password_confirmation%>
          </div>
          <div class='field-input'>
            <%= f.password_field :password_confirmation, autocomplete: "off"%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Create Account", class: 'btn'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page-profile-top'>
    <div class='account-page__inner--left account-page__header'>
      <h2><%=link_to "My-account", root_path,class:"my-account"%></h2>
      <div class="select-option">
        <div class="edit-btn">
          <% if user_signed_in? && current_user.id == @user.id%>
            <%= link_to ">>Edit", edit_user_path(current_user.id), class: "my-account" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class='account-page-profile user-form'>
      <div class="image">
        <% if @user.image.attached? %>
          <%= image_tag @user.image %>
        <% end %>
      </div>
      <table class="table">
        <tbody>
          <tr>
            <th class="detail-user">nickname</th>
            <td class="detail-value"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="detail-user">self-introduction</th>
            <td class="detail-value"><%= @user.self_introduction %></td>
          </tr>
          <tr>
            <th class="detail-user">country</th>
            <td class="detail-value"><%= @user.country.name%></td>
          </tr>
          <tr>
            <th class="detail-user">gender</th>
            <td class="detail-value"><%= @user.gender.name %></td>
          </tr>
          <tr>
            <th class="detail-user">age</th>
            <td class="detail-value"><%= @user.age %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="contents_row">
    <% @articles.each do |article| %>
      <%= render partial: "show-form", locals: { article: article } %>
    <% end %>
  </div>
</div>